using System.Data;
using System.Text.Json;
using Erp.Application.Authorization;
using Erp.Application.Commands;
using Erp.Application.DTOs;
using Erp.Application.Exceptions;
using Erp.Application.Interfaces;
using Erp.Domain.Entities;
using Erp.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Npgsql;

namespace Erp.Infrastructure.Services;

public sealed class InventoryCommandService : IInventoryCommandService
{
    private const int MaxRetryCount = 3;

    private readonly IDbContextFactory<ErpDbContext> _dbContextFactory;
    private readonly IAccessControl _accessControl;
    private readonly ICurrentUserContext _currentUserContext;

    public InventoryCommandService(
        IDbContextFactory<ErpDbContext> dbContextFactory,
        IAccessControl accessControl,
        ICurrentUserContext currentUserContext)
    {
        _dbContextFactory = dbContextFactory;
        _accessControl = accessControl;
        _currentUserContext = currentUserContext;
    }

    public Task<StockTransactionResultDto> ReceiveStockAsync(
        ReceiveStockCommand command,
        CancellationToken cancellationToken = default)
    {
        if (command is null)
        {
            throw new InvalidOperationException("Request payload is required.");
        }

        var lines = command.Lines.Select(line => new StockMutationLine(
            line.ItemId,
            line.Qty,
            line.UnitCost,
            line.Note)).ToList();

        return ProcessAsync(
            requestedTxNo: command.TxNo,
            txNoPrefix: "RCPT",
            txType: InventoryTxType.Receipt,
            auditAction: "Stock.Receipt",
            warehouseId: command.WarehouseId,
            locationId: command.LocationId,
            occurredAtUtc: command.OccurredAtUtc,
            lines: lines,
            cancellationToken: cancellationToken);
    }

    public Task<StockTransactionResultDto> IssueStockAsync(
        IssueStockCommand command,
        CancellationToken cancellationToken = default)
    {
        if (command is null)
        {
            throw new InvalidOperationException("Request payload is required.");
        }

        var lines = command.Lines.Select(line => new StockMutationLine(
            line.ItemId,
            -line.Qty,
            UnitCost: null,
            line.Note)).ToList();

        return ProcessAsync(
            requestedTxNo: command.TxNo,
            txNoPrefix: "ISS",
            txType: InventoryTxType.Issue,
            auditAction: "Stock.Issue",
            warehouseId: command.WarehouseId,
            locationId: command.LocationId,
            occurredAtUtc: command.OccurredAtUtc,
            lines: lines,
            cancellationToken: cancellationToken);
    }

    private async Task<StockTransactionResultDto> ProcessAsync(
        string? requestedTxNo,
        string txNoPrefix,
        InventoryTxType txType,
        string auditAction,
        Guid warehouseId,
        Guid? locationId,
        DateTime occurredAtUtc,
        IReadOnlyList<StockMutationLine> lines,
        CancellationToken cancellationToken)
    {
        _accessControl.DemandPermission(PermissionCodes.InventoryStockWrite);

        ValidateRequest(warehouseId, locationId, lines);

        var normalizedLocationId = NormalizeOptionalGuid(locationId);
        var normalizedOccurredAtUtc = NormalizeUtc(occurredAtUtc);
        var requestedTxNoNormalized = NormalizeTxNo(requestedTxNo);
        var autoGeneratedTxNo = string.IsNullOrWhiteSpace(requestedTxNoNormalized);

        for (var attempt = 1; attempt <= MaxRetryCount; attempt++)
        {
            await using var db = await _dbContextFactory.CreateDbContextAsync(cancellationToken);
            await using var tx = await db.Database.BeginTransactionAsync(IsolationLevel.Serializable, cancellationToken);

            try
            {
                await EnsureWarehouseAndLocationAsync(db, warehouseId, normalizedLocationId, cancellationToken);
                await EnsureItemsExistAsync(db, lines.Select(x => x.ItemId), cancellationToken);

                var effectiveTxNo = requestedTxNoNormalized;
                if (autoGeneratedTxNo)
                {
                    effectiveTxNo = await GenerateTxNoAsync(db, txNoPrefix, normalizedOccurredAtUtc, cancellationToken);
                }

                var itemIds = lines.Select(x => x.ItemId).Distinct().ToArray();
                var balances = await db.InventoryBalances
                    .Where(x =>
                        x.WarehouseId == warehouseId &&
                        x.LocationId == normalizedLocationId &&
                        itemIds.Contains(x.ItemId))
                    .ToDictionaryAsync(x => x.ItemId, cancellationToken);

                foreach (var line in lines)
                {
                    db.StockLedgerEntries.Add(new StockLedgerEntry(
                        txNo: effectiveTxNo!,
                        txType: txType,
                        itemId: line.ItemId,
                        warehouseId: warehouseId,
                        qty: line.SignedQty,
                        occurredAtUtc: normalizedOccurredAtUtc,
                        locationId: normalizedLocationId,
                        unitCost: line.UnitCost,
                        referenceType: StockReferenceType.Manual,
                        referenceId: null,
                        note: line.Note,
                        actorUserId: _currentUserContext.CurrentUserId));

                    if (!balances.TryGetValue(line.ItemId, out var balance))
                    {
                        if (line.SignedQty < 0m)
                        {
                            throw new InvalidOperationException($"Insufficient stock for item '{line.ItemId}'.");
                        }

                        balance = new InventoryBalance(
                            itemId: line.ItemId,
                            warehouseId: warehouseId,
                            locationId: normalizedLocationId,
                            qtyOnHand: line.SignedQty);

                        db.InventoryBalances.Add(balance);
                        balances[line.ItemId] = balance;
                    }
                    else
                    {
                        var nextQty = balance.QtyOnHand + line.SignedQty;
                        if (nextQty < 0m)
                        {
                            throw new InvalidOperationException($"Insufficient stock for item '{line.ItemId}'.");
                        }

                        balance.ApplyOnHandDelta(line.SignedQty);
                    }
                }

                db.AuditLogs.Add(new AuditLog(
                    actorUserId: _currentUserContext.CurrentUserId,
                    action: auditAction,
                    target: effectiveTxNo,
                    detailJson: SerializeAuditDetail(effectiveTxNo!, warehouseId, normalizedLocationId, normalizedOccurredAtUtc, lines),
                    ip: null));

                await db.SaveChangesAsync(cancellationToken);
                await tx.CommitAsync(cancellationToken);

                return new StockTransactionResultDto(
                    TxNo: effectiveTxNo!,
                    LineCount: lines.Count,
                    OccurredAtUtc: normalizedOccurredAtUtc,
                    ProcessedAtUtc: DateTime.UtcNow);
            }
            catch (DbUpdateConcurrencyException) when (attempt < MaxRetryCount)
            {
                await tx.RollbackAsync(cancellationToken);
                continue;
            }
            catch (DbUpdateException ex) when (attempt < MaxRetryCount && IsRetriable(ex, autoGeneratedTxNo))
            {
                await tx.RollbackAsync(cancellationToken);
                continue;
            }
            catch (DbUpdateException ex) when (IsDuplicateTxNo(ex))
            {
                await tx.RollbackAsync(cancellationToken);
                throw new InvalidOperationException("Duplicate TxNo.");
            }
        }

        throw new ConcurrencyException("Concurrency conflict detected. Please retry.");
    }

    private static void ValidateRequest(Guid warehouseId, Guid? locationId, IReadOnlyList<StockMutationLine> lines)
    {
        if (warehouseId == Guid.Empty)
        {
            throw new InvalidOperationException("WarehouseId is required.");
        }

        if (locationId.HasValue && locationId.Value == Guid.Empty)
        {
            throw new InvalidOperationException("LocationId is invalid.");
        }

        if (lines.Count == 0)
        {
            throw new InvalidOperationException("At least one line is required.");
        }

        foreach (var line in lines)
        {
            if (line.ItemId == Guid.Empty)
            {
                throw new InvalidOperationException("ItemId is required.");
            }

            if (line.SignedQty == 0m)
            {
                throw new InvalidOperationException("Qty must be non-zero.");
            }

            if (line.UnitCost.HasValue && line.UnitCost.Value < 0m)
            {
                throw new InvalidOperationException("UnitCost cannot be negative.");
            }
        }
    }

    private static async Task EnsureWarehouseAndLocationAsync(
        ErpDbContext db,
        Guid warehouseId,
        Guid? locationId,
        CancellationToken cancellationToken)
    {
        var warehouse = await db.Warehouses.FirstOrDefaultAsync(x => x.Id == warehouseId, cancellationToken);
        if (warehouse is null)
        {
            throw new InvalidOperationException("Warehouse not found.");
        }

        if (!warehouse.IsActive)
        {
            throw new InvalidOperationException("Warehouse is inactive.");
        }

        if (!locationId.HasValue)
        {
            return;
        }

        var location = await db.Locations.FirstOrDefaultAsync(x => x.Id == locationId.Value, cancellationToken);
        if (location is null)
        {
            throw new InvalidOperationException("Location not found.");
        }

        if (!location.IsActive)
        {
            throw new InvalidOperationException("Location is inactive.");
        }

        if (location.WarehouseId != warehouseId)
        {
            throw new InvalidOperationException("Location does not belong to the selected warehouse.");
        }
    }

    private static async Task EnsureItemsExistAsync(
        ErpDbContext db,
        IEnumerable<Guid> itemIds,
        CancellationToken cancellationToken)
    {
        var requiredIds = itemIds.Distinct().ToArray();
        var existingIds = await db.Items
            .Where(x => requiredIds.Contains(x.Id))
            .Select(x => x.Id)
            .ToArrayAsync(cancellationToken);

        if (existingIds.Length != requiredIds.Length)
        {
            throw new InvalidOperationException("One or more items were not found.");
        }
    }

    private static async Task<string> GenerateTxNoAsync(
        ErpDbContext db,
        string prefix,
        DateTime occurredAtUtc,
        CancellationToken cancellationToken)
    {
        var datePart = occurredAtUtc.ToString("yyyyMMdd");
        var txPrefix = $"{prefix}-{datePart}-";

        var lastTxNo = await db.StockLedgerEntries
            .AsNoTracking()
            .Where(x => x.TxNo.StartsWith(txPrefix))
            .OrderByDescending(x => x.TxNo)
            .Select(x => x.TxNo)
            .FirstOrDefaultAsync(cancellationToken);

        var nextSequence = 1;
        if (!string.IsNullOrWhiteSpace(lastTxNo))
        {
            var rawSequence = lastTxNo[(txPrefix.Length)..];
            if (int.TryParse(rawSequence, out var sequence))
            {
                nextSequence = sequence + 1;
            }
        }

        return $"{txPrefix}{nextSequence:0000}";
    }

    private static bool IsRetriable(DbUpdateException exception, bool autoGeneratedTxNo)
    {
        return IsSerializationFailure(exception) || (autoGeneratedTxNo && IsDuplicateTxNo(exception));
    }

    private static bool IsSerializationFailure(DbUpdateException exception)
    {
        return exception.InnerException is PostgresException pg
            && string.Equals(pg.SqlState, PostgresErrorCodes.SerializationFailure, StringComparison.Ordinal);
    }

    private static bool IsDuplicateTxNo(DbUpdateException exception)
    {
        return exception.InnerException is PostgresException pg
            && string.Equals(pg.SqlState, PostgresErrorCodes.UniqueViolation, StringComparison.Ordinal)
            && string.Equals(pg.ConstraintName, "IX_stock_ledger_entries_tx_no", StringComparison.Ordinal);
    }

    private static string SerializeAuditDetail(
        string txNo,
        Guid warehouseId,
        Guid? locationId,
        DateTime occurredAtUtc,
        IReadOnlyList<StockMutationLine> lines)
    {
        var detail = new
        {
            txNo,
            warehouseId,
            locationId,
            occurredAtUtc,
            lineCount = lines.Count,
            lines = lines.Select(x => new
            {
                x.ItemId,
                Qty = Math.Abs(x.SignedQty),
                SignedQty = x.SignedQty,
                x.UnitCost,
                x.Note
            })
        };

        return JsonSerializer.Serialize(detail);
    }

    private static DateTime NormalizeUtc(DateTime value)
    {
        if (value == default)
        {
            return DateTime.UtcNow;
        }

        return value.Kind == DateTimeKind.Utc ? value : value.ToUniversalTime();
    }

    private static Guid? NormalizeOptionalGuid(Guid? value)
    {
        if (!value.HasValue || value.Value == Guid.Empty)
        {
            return null;
        }

        return value.Value;
    }

    private static string? NormalizeTxNo(string? txNo)
    {
        return string.IsNullOrWhiteSpace(txNo) ? null : txNo.Trim();
    }

    private sealed record StockMutationLine(
        Guid ItemId,
        decimal SignedQty,
        decimal? UnitCost,
        string? Note);
}
