using System.Data;
using System.Text.Json;
using System.Text.RegularExpressions;
using Erp.Application.Authorization;
using Erp.Application.Commands;
using Erp.Application.DTOs;
using Erp.Application.Exceptions;
using Erp.Application.Interfaces;
using Erp.Domain.Entities;
using Erp.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Npgsql;

namespace Erp.Infrastructure.Services;

public sealed class InventoryCommandService : IInventoryCommandService
{
    private const int MaxRetryCount = 3;

    private readonly IDbContextFactory<ErpDbContext> _dbContextFactory;
    private readonly IAccessControl _accessControl;
    private readonly ICurrentUserContext _currentUserContext;

    public InventoryCommandService(
        IDbContextFactory<ErpDbContext> dbContextFactory,
        IAccessControl accessControl,
        ICurrentUserContext currentUserContext)
    {
        _dbContextFactory = dbContextFactory;
        _accessControl = accessControl;
        _currentUserContext = currentUserContext;
    }

    public Task<StockTransactionResultDto> AdjustStockByCountAsync(
        AdjustStockByCountCommand command,
        CancellationToken cancellationToken = default)
    {
        if (command is null)
        {
            throw new InvalidOperationException("Request payload is required.");
        }

        var lines = command.Lines.Select(line => new StockCountLine(
            line.ItemId,
            line.CountedQty,
            line.Note)).ToList();

        return ProcessAdjustByCountAsync(
            requestedTxNo: command.TxNo,
            warehouseId: command.WarehouseId,
            locationId: command.LocationId,
            occurredAtUtc: command.OccurredAtUtc,
            lines: lines,
            cancellationToken: cancellationToken);
    }

    public Task<StockTransactionResultDto> ReceiveStockAsync(
        ReceiveStockCommand command,
        CancellationToken cancellationToken = default)
    {
        if (command is null)
        {
            throw new InvalidOperationException("Request payload is required.");
        }

        var lines = command.Lines.Select(line => new StockMutationLine(
            line.ItemId,
            line.Qty,
            line.UnitCost,
            line.Note,
            line.LotNo,
            line.SerialNo,
            line.ExpiryDate)).ToList();

        return ProcessAsync(
            requestedTxNo: command.TxNo,
            requiredPermission: PermissionCodes.InventoryStockReceipt,
            txNoPrefix: "RCPT",
            txType: InventoryTxType.Receipt,
            auditAction: "Stock.Receipt",
            warehouseId: command.WarehouseId,
            locationId: command.LocationId,
            occurredAtUtc: command.OccurredAtUtc,
            lines: lines,
            cancellationToken: cancellationToken);
    }

    public Task<StockTransactionResultDto> IssueStockAsync(
        IssueStockCommand command,
        CancellationToken cancellationToken = default)
    {
        if (command is null)
        {
            throw new InvalidOperationException("Request payload is required.");
        }

        var lines = command.Lines.Select(line => new StockMutationLine(
            line.ItemId,
            -line.Qty,
            UnitCost: null,
            line.Note,
            line.LotNo,
            line.SerialNo,
            ExpiryDate: null)).ToList();

        return ProcessAsync(
            requestedTxNo: command.TxNo,
            requiredPermission: PermissionCodes.InventoryStockIssue,
            txNoPrefix: "ISS",
            txType: InventoryTxType.Issue,
            auditAction: "Stock.Issue",
            warehouseId: command.WarehouseId,
            locationId: command.LocationId,
            occurredAtUtc: command.OccurredAtUtc,
            lines: lines,
            cancellationToken: cancellationToken);
    }

    private async Task<StockTransactionResultDto> ProcessAdjustByCountAsync(
        string? requestedTxNo,
        Guid warehouseId,
        Guid? locationId,
        DateTime occurredAtUtc,
        IReadOnlyList<StockCountLine> lines,
        CancellationToken cancellationToken)
    {
        _accessControl.DemandPermission(PermissionCodes.InventoryStockAdjust);
        ValidateStockCountRequest(warehouseId, locationId, lines);

        var normalizedLocationId = NormalizeOptionalGuid(locationId);
        var normalizedOccurredAtUtc = NormalizeUtc(occurredAtUtc);
        var requestedTxNoNormalized = NormalizeTxNo(requestedTxNo);
        if (!string.IsNullOrWhiteSpace(requestedTxNoNormalized))
        {
            ValidateRequestedTxNo(requestedTxNoNormalized, "ADJ");
        }

        var autoGeneratedTxNo = string.IsNullOrWhiteSpace(requestedTxNoNormalized);

        for (var attempt = 1; attempt <= MaxRetryCount; attempt++)
        {
            await using var db = await _dbContextFactory.CreateDbContextAsync(cancellationToken);
            await using var tx = await db.Database.BeginTransactionAsync(IsolationLevel.Serializable, cancellationToken);

            try
            {
                await EnsureWarehouseAndLocationAsync(db, warehouseId, normalizedLocationId, cancellationToken);
                _ = await LoadItemTrackingTypesAsync(db, lines.Select(x => x.ItemId), cancellationToken);

                var effectiveTxNo = requestedTxNoNormalized;
                if (autoGeneratedTxNo)
                {
                    effectiveTxNo = await GenerateTxNoAsync(db, "ADJ", normalizedOccurredAtUtc, cancellationToken);
                }
                else
                {
                    await EnsureTxNoNotExistsAsync(db, effectiveTxNo!, cancellationToken);
                }

                var itemIds = lines.Select(x => x.ItemId).Distinct().ToArray();
                var balances = await db.InventoryBalances
                    .Where(x =>
                        x.WarehouseId == warehouseId &&
                        x.LocationId == normalizedLocationId &&
                        itemIds.Contains(x.ItemId))
                    .ToDictionaryAsync(x => x.ItemId, cancellationToken);

                var appliedLines = new List<AppliedStockCountLine>(lines.Count);

                foreach (var line in lines)
                {
                    balances.TryGetValue(line.ItemId, out var balance);
                    var currentQty = balance?.QtyOnHand ?? 0m;
                    var diff = line.CountedQty - currentQty;

                    if (diff == 0m)
                    {
                        continue;
                    }

                    var txType = diff > 0m ? InventoryTxType.AdjustIn : InventoryTxType.AdjustOut;

                    db.StockLedgerEntries.Add(new StockLedgerEntry(
                        txNo: effectiveTxNo!,
                        txType: txType,
                        itemId: line.ItemId,
                        warehouseId: warehouseId,
                        qty: diff,
                        occurredAtUtc: normalizedOccurredAtUtc,
                        locationId: normalizedLocationId,
                        unitCost: null,
                        referenceType: StockReferenceType.StockCount,
                        referenceId: null,
                        note: line.Note,
                        actorUserId: _currentUserContext.CurrentUserId));

                    if (balance is null)
                    {
                        balance = new InventoryBalance(
                            itemId: line.ItemId,
                            warehouseId: warehouseId,
                            locationId: normalizedLocationId,
                            qtyOnHand: diff);

                        db.InventoryBalances.Add(balance);
                        balances[line.ItemId] = balance;
                    }
                    else
                    {
                        balance.ApplyOnHandDelta(diff);
                    }

                    appliedLines.Add(new AppliedStockCountLine(
                        line.ItemId,
                        currentQty,
                        line.CountedQty,
                        diff,
                        line.Note));
                }

                db.AuditLogs.Add(new AuditLog(
                    actorUserId: _currentUserContext.CurrentUserId,
                    action: "Stock.AdjustByCount",
                    target: effectiveTxNo,
                    detailJson: SerializeStockCountAuditDetail(
                        effectiveTxNo!,
                        warehouseId,
                        normalizedLocationId,
                        normalizedOccurredAtUtc,
                        lines,
                        appliedLines),
                    ip: null));

                await db.SaveChangesAsync(cancellationToken);
                await tx.CommitAsync(cancellationToken);

                return new StockTransactionResultDto(
                    TxNo: effectiveTxNo!,
                    LineCount: appliedLines.Count,
                    OccurredAtUtc: normalizedOccurredAtUtc,
                    ProcessedAtUtc: DateTime.UtcNow);
            }
            catch (DbUpdateConcurrencyException) when (attempt < MaxRetryCount)
            {
                await tx.RollbackAsync(cancellationToken);
                continue;
            }
            catch (DbUpdateException ex) when (attempt < MaxRetryCount && IsRetriable(ex, autoGeneratedTxNo))
            {
                await tx.RollbackAsync(cancellationToken);
                continue;
            }
            catch (DbUpdateException ex) when (IsDuplicateTxNo(ex))
            {
                await tx.RollbackAsync(cancellationToken);
                throw new InvalidOperationException("Duplicate TxNo.");
            }
        }

        throw new ConcurrencyException("Concurrency conflict detected. Please retry.");
    }

    private async Task<StockTransactionResultDto> ProcessAsync(
        string? requestedTxNo,
        string requiredPermission,
        string txNoPrefix,
        InventoryTxType txType,
        string auditAction,
        Guid warehouseId,
        Guid? locationId,
        DateTime occurredAtUtc,
        IReadOnlyList<StockMutationLine> lines,
        CancellationToken cancellationToken)
    {
        _accessControl.DemandPermission(requiredPermission);

        ValidateRequest(warehouseId, locationId, lines);

        var normalizedLocationId = NormalizeOptionalGuid(locationId);
        var normalizedOccurredAtUtc = NormalizeUtc(occurredAtUtc);
        var requestedTxNoNormalized = NormalizeTxNo(requestedTxNo);
        if (!string.IsNullOrWhiteSpace(requestedTxNoNormalized))
        {
            ValidateRequestedTxNo(requestedTxNoNormalized, txNoPrefix);
        }

        var autoGeneratedTxNo = string.IsNullOrWhiteSpace(requestedTxNoNormalized);

        for (var attempt = 1; attempt <= MaxRetryCount; attempt++)
        {
            await using var db = await _dbContextFactory.CreateDbContextAsync(cancellationToken);
            await using var tx = await db.Database.BeginTransactionAsync(IsolationLevel.Serializable, cancellationToken);

            try
            {
                await EnsureWarehouseAndLocationAsync(db, warehouseId, normalizedLocationId, cancellationToken);
                var itemTrackingTypes = await LoadItemTrackingTypesAsync(db, lines.Select(x => x.ItemId), cancellationToken);
                var lotMap = await LoadLotMapAsync(db, lines, cancellationToken);

                var effectiveTxNo = requestedTxNoNormalized;
                if (autoGeneratedTxNo)
                {
                    effectiveTxNo = await GenerateTxNoAsync(db, txNoPrefix, normalizedOccurredAtUtc, cancellationToken);
                }
                else
                {
                    await EnsureTxNoNotExistsAsync(db, effectiveTxNo!, cancellationToken);
                }

                var itemIds = lines.Select(x => x.ItemId).Distinct().ToArray();
                var balances = await db.InventoryBalances
                    .Where(x =>
                        x.WarehouseId == warehouseId &&
                        x.LocationId == normalizedLocationId &&
                        itemIds.Contains(x.ItemId))
                    .ToDictionaryAsync(x => x.ItemId, cancellationToken);

                foreach (var line in lines)
                {
                    var tracking = itemTrackingTypes[line.ItemId];
                    var trackingInfo = await ResolveTrackingAsync(
                        db,
                        txType,
                        warehouseId,
                        normalizedLocationId,
                        line,
                        tracking,
                        lotMap,
                        cancellationToken);

                    db.StockLedgerEntries.Add(new StockLedgerEntry(
                        txNo: effectiveTxNo!,
                        txType: txType,
                        itemId: line.ItemId,
                        warehouseId: warehouseId,
                        qty: line.SignedQty,
                        occurredAtUtc: normalizedOccurredAtUtc,
                        locationId: normalizedLocationId,
                        lotId: trackingInfo.LotId,
                        serialNo: trackingInfo.SerialNo,
                        expiryDate: trackingInfo.ExpiryDate,
                        unitCost: line.UnitCost,
                        referenceType: StockReferenceType.Manual,
                        referenceId: null,
                        note: line.Note,
                        actorUserId: _currentUserContext.CurrentUserId));

                    if (!balances.TryGetValue(line.ItemId, out var balance))
                    {
                        if (line.SignedQty < 0m)
                        {
                            throw new InvalidOperationException($"Insufficient stock for item '{line.ItemId}'.");
                        }

                        balance = new InventoryBalance(
                            itemId: line.ItemId,
                            warehouseId: warehouseId,
                            locationId: normalizedLocationId,
                            qtyOnHand: line.SignedQty);

                        db.InventoryBalances.Add(balance);
                        balances[line.ItemId] = balance;
                    }
                    else
                    {
                        var nextQty = balance.QtyOnHand + line.SignedQty;
                        if (nextQty < 0m)
                        {
                            throw new InvalidOperationException($"Insufficient stock for item '{line.ItemId}'.");
                        }

                        balance.ApplyOnHandDelta(line.SignedQty);
                    }
                }

                db.AuditLogs.Add(new AuditLog(
                    actorUserId: _currentUserContext.CurrentUserId,
                    action: auditAction,
                    target: effectiveTxNo,
                    detailJson: SerializeAuditDetail(effectiveTxNo!, warehouseId, normalizedLocationId, normalizedOccurredAtUtc, lines),
                    ip: null));

                await db.SaveChangesAsync(cancellationToken);
                await tx.CommitAsync(cancellationToken);

                return new StockTransactionResultDto(
                    TxNo: effectiveTxNo!,
                    LineCount: lines.Count,
                    OccurredAtUtc: normalizedOccurredAtUtc,
                    ProcessedAtUtc: DateTime.UtcNow);
            }
            catch (DbUpdateConcurrencyException) when (attempt < MaxRetryCount)
            {
                await tx.RollbackAsync(cancellationToken);
                continue;
            }
            catch (DbUpdateException ex) when (attempt < MaxRetryCount && IsRetriable(ex, autoGeneratedTxNo))
            {
                await tx.RollbackAsync(cancellationToken);
                continue;
            }
            catch (DbUpdateException ex) when (IsDuplicateTxNo(ex))
            {
                await tx.RollbackAsync(cancellationToken);
                throw new InvalidOperationException("Duplicate TxNo.");
            }
        }

        throw new ConcurrencyException("Concurrency conflict detected. Please retry.");
    }

    private static void ValidateRequest(Guid warehouseId, Guid? locationId, IReadOnlyList<StockMutationLine> lines)
    {
        if (warehouseId == Guid.Empty)
        {
            throw new InvalidOperationException("WarehouseId is required.");
        }

        if (locationId.HasValue && locationId.Value == Guid.Empty)
        {
            throw new InvalidOperationException("LocationId is invalid.");
        }

        if (lines.Count == 0)
        {
            throw new InvalidOperationException("At least one line is required.");
        }

        foreach (var line in lines)
        {
            if (line.ItemId == Guid.Empty)
            {
                throw new InvalidOperationException("ItemId is required.");
            }

            if (line.SignedQty == 0m)
            {
                throw new InvalidOperationException("Qty must be non-zero.");
            }

            if (line.UnitCost.HasValue && line.UnitCost.Value < 0m)
            {
                throw new InvalidOperationException("UnitCost cannot be negative.");
            }
        }
    }

    private static void ValidateStockCountRequest(Guid warehouseId, Guid? locationId, IReadOnlyList<StockCountLine> lines)
    {
        if (warehouseId == Guid.Empty)
        {
            throw new InvalidOperationException("WarehouseId is required.");
        }

        if (locationId.HasValue && locationId.Value == Guid.Empty)
        {
            throw new InvalidOperationException("LocationId is invalid.");
        }

        if (lines.Count == 0)
        {
            throw new InvalidOperationException("At least one line is required.");
        }

        var distinctItems = new HashSet<Guid>();
        foreach (var line in lines)
        {
            if (line.ItemId == Guid.Empty)
            {
                throw new InvalidOperationException("ItemId is required.");
            }

            if (!distinctItems.Add(line.ItemId))
            {
                throw new InvalidOperationException("Duplicate ItemId is not allowed in count lines.");
            }

            if (line.CountedQty < 0m)
            {
                throw new InvalidOperationException("CountedQty cannot be negative.");
            }
        }
    }

    private static async Task EnsureWarehouseAndLocationAsync(
        ErpDbContext db,
        Guid warehouseId,
        Guid? locationId,
        CancellationToken cancellationToken)
    {
        var warehouse = await db.Warehouses.FirstOrDefaultAsync(x => x.Id == warehouseId, cancellationToken);
        if (warehouse is null)
        {
            throw new InvalidOperationException("Warehouse not found.");
        }

        if (!warehouse.IsActive)
        {
            throw new InvalidOperationException("Warehouse is inactive.");
        }

        if (!locationId.HasValue)
        {
            return;
        }

        var location = await db.Locations.FirstOrDefaultAsync(x => x.Id == locationId.Value, cancellationToken);
        if (location is null)
        {
            throw new InvalidOperationException("Location not found.");
        }

        if (!location.IsActive)
        {
            throw new InvalidOperationException("Location is inactive.");
        }

        if (location.WarehouseId != warehouseId)
        {
            throw new InvalidOperationException("Location does not belong to the selected warehouse.");
        }
    }

    private static async Task<Dictionary<Guid, TrackingType>> LoadItemTrackingTypesAsync(
        ErpDbContext db,
        IEnumerable<Guid> itemIds,
        CancellationToken cancellationToken)
    {
        var requiredIds = itemIds.Distinct().ToArray();
        var items = await db.Items
            .AsNoTracking()
            .Where(x => requiredIds.Contains(x.Id))
            .Select(x => new { x.Id, x.TrackingType })
            .ToListAsync(cancellationToken);

        if (items.Count != requiredIds.Length)
        {
            throw new InvalidOperationException("One or more items were not found.");
        }

        return items.ToDictionary(x => x.Id, x => x.TrackingType);
    }

    private static async Task<Dictionary<StockLotKey, StockLot>> LoadLotMapAsync(
        ErpDbContext db,
        IReadOnlyList<StockMutationLine> lines,
        CancellationToken cancellationToken)
    {
        var lotKeys = lines
            .Select(x => new { x.ItemId, LotNo = NormalizeLotNo(x.LotNo) })
            .Where(x => x.LotNo is not null)
            .Select(x => new StockLotKey(x.ItemId, x.LotNo!))
            .Distinct()
            .ToArray();

        if (lotKeys.Length == 0)
        {
            return new Dictionary<StockLotKey, StockLot>();
        }

        var itemIds = lotKeys.Select(x => x.ItemId).Distinct().ToArray();
        var lotNos = lotKeys.Select(x => x.LotNo).Distinct(StringComparer.Ordinal).ToArray();
        var lots = await db.StockLots
            .Where(x => itemIds.Contains(x.ItemId) && lotNos.Contains(x.LotNo))
            .ToListAsync(cancellationToken);

        var map = new Dictionary<StockLotKey, StockLot>();
        foreach (var lot in lots)
        {
            map[new StockLotKey(lot.ItemId, lot.LotNo)] = lot;
        }

        return map;
    }

    private async Task<TrackingResolution> ResolveTrackingAsync(
        ErpDbContext db,
        InventoryTxType txType,
        Guid warehouseId,
        Guid? locationId,
        StockMutationLine line,
        TrackingType trackingType,
        IDictionary<StockLotKey, StockLot> lotMap,
        CancellationToken cancellationToken)
    {
        var qty = Math.Abs(line.SignedQty);
        var lotNo = NormalizeLotNo(line.LotNo);
        var serialNo = NormalizeSerialNo(line.SerialNo);
        var expiryDate = NormalizeDate(line.ExpiryDate);

        if (trackingType == TrackingType.Serial)
        {
            if (qty != 1m)
            {
                throw new InvalidOperationException("Serial-tracked item quantity must be 1 per line.");
            }

            if (string.IsNullOrWhiteSpace(serialNo))
            {
                throw new InvalidOperationException("SerialNo is required for serial-tracked items.");
            }

            if (txType == InventoryTxType.Receipt)
            {
                var onHand = await GetSerialOnHandAsync(
                    db,
                    line.ItemId,
                    warehouseId,
                    locationId,
                    serialNo,
                    cancellationToken);

                if (onHand > 0m)
                {
                    throw new InvalidOperationException($"Serial '{serialNo}' is already in stock.");
                }
            }
            else
            {
                var onHand = await GetSerialOnHandAsync(
                    db,
                    line.ItemId,
                    warehouseId,
                    locationId,
                    serialNo,
                    cancellationToken);

                if (onHand < qty)
                {
                    throw new InvalidOperationException($"Insufficient stock for serial '{serialNo}'.");
                }
            }

            return new TrackingResolution(null, serialNo, expiryDate);
        }

        var requiresLot = trackingType is TrackingType.Lot or TrackingType.Batch or TrackingType.Expiry;
        if (!requiresLot)
        {
            return new TrackingResolution(null, serialNo, expiryDate);
        }

        if (string.IsNullOrWhiteSpace(lotNo))
        {
            throw new InvalidOperationException("LotNo is required for lot-tracked items.");
        }

        var key = new StockLotKey(line.ItemId, lotNo);
        if (!lotMap.TryGetValue(key, out var lot))
        {
            if (txType != InventoryTxType.Receipt)
            {
                throw new InvalidOperationException($"Lot '{lotNo}' was not found for item '{line.ItemId}'.");
            }

            if (trackingType == TrackingType.Expiry && !expiryDate.HasValue)
            {
                throw new InvalidOperationException("ExpiryDate is required for expiry-tracked items.");
            }

            lot = new StockLot(line.ItemId, lotNo, expiryDate);
            db.StockLots.Add(lot);
            lotMap[key] = lot;
        }
        else if (trackingType == TrackingType.Expiry)
        {
            if (!expiryDate.HasValue)
            {
                if (!lot.ExpiryDate.HasValue)
                {
                    throw new InvalidOperationException("ExpiryDate is required for expiry-tracked items.");
                }
            }
            else
            {
                lot.EnsureExpiryDate(expiryDate.Value);
            }
        }

        if (txType == InventoryTxType.Issue)
        {
            var onHand = await GetLotOnHandAsync(
                db,
                line.ItemId,
                warehouseId,
                locationId,
                lot.Id,
                cancellationToken);

            if (onHand < qty)
            {
                throw new InvalidOperationException($"Insufficient stock for lot '{lotNo}'.");
            }
        }

        return new TrackingResolution(lot.Id, null, lot.ExpiryDate ?? expiryDate);
    }

    private static async Task<decimal> GetLotOnHandAsync(
        ErpDbContext db,
        Guid itemId,
        Guid warehouseId,
        Guid? locationId,
        Guid lotId,
        CancellationToken cancellationToken)
    {
        var query = db.StockLedgerEntries.Where(x =>
            x.ItemId == itemId &&
            x.WarehouseId == warehouseId &&
            x.LocationId == locationId &&
            x.LotId == lotId);

        var sum = await query.SumAsync(x => (decimal?)x.Qty, cancellationToken);
        return sum ?? 0m;
    }

    private static async Task<decimal> GetSerialOnHandAsync(
        ErpDbContext db,
        Guid itemId,
        Guid warehouseId,
        Guid? locationId,
        string serialNo,
        CancellationToken cancellationToken)
    {
        var query = db.StockLedgerEntries.Where(x =>
            x.ItemId == itemId &&
            x.WarehouseId == warehouseId &&
            x.LocationId == locationId &&
            x.SerialNo == serialNo);

        var sum = await query.SumAsync(x => (decimal?)x.Qty, cancellationToken);
        return sum ?? 0m;
    }

    private static async Task<string> GenerateTxNoAsync(
        ErpDbContext db,
        string prefix,
        DateTime occurredAtUtc,
        CancellationToken cancellationToken)
    {
        var datePart = occurredAtUtc.ToString("yyyyMMdd");
        var txPrefix = $"{prefix}-{datePart}-";

        var lastTxNo = await db.StockLedgerEntries
            .AsNoTracking()
            .Where(x => x.TxNo.StartsWith(txPrefix))
            .OrderByDescending(x => x.TxNo)
            .Select(x => x.TxNo)
            .FirstOrDefaultAsync(cancellationToken);

        var nextSequence = 1;
        if (!string.IsNullOrWhiteSpace(lastTxNo))
        {
            var rawSequence = lastTxNo[(txPrefix.Length)..];
            if (int.TryParse(rawSequence, out var sequence))
            {
                nextSequence = sequence + 1;
            }
        }

        return $"{txPrefix}{nextSequence:0000}";
    }

    private static async Task EnsureTxNoNotExistsAsync(
        ErpDbContext db,
        string txNo,
        CancellationToken cancellationToken)
    {
        var exists = await db.StockLedgerEntries
            .AsNoTracking()
            .AnyAsync(x => x.TxNo == txNo, cancellationToken);

        if (exists)
        {
            throw new InvalidOperationException("Duplicate TxNo.");
        }
    }

    private static bool IsRetriable(DbUpdateException exception, bool autoGeneratedTxNo)
    {
        return IsSerializationFailure(exception)
            || IsDuplicateStockLot(exception)
            || (autoGeneratedTxNo && IsDuplicateTxNo(exception));
    }

    private static bool IsSerializationFailure(DbUpdateException exception)
    {
        return exception.InnerException is PostgresException pg
            && string.Equals(pg.SqlState, PostgresErrorCodes.SerializationFailure, StringComparison.Ordinal);
    }

    private static bool IsDuplicateTxNo(DbUpdateException exception)
    {
        return exception.InnerException is PostgresException pg
            && string.Equals(pg.SqlState, PostgresErrorCodes.UniqueViolation, StringComparison.Ordinal)
            && string.Equals(pg.ConstraintName, "IX_stock_ledger_entries_tx_no", StringComparison.Ordinal);
    }

    private static bool IsDuplicateStockLot(DbUpdateException exception)
    {
        return exception.InnerException is PostgresException pg
            && string.Equals(pg.SqlState, PostgresErrorCodes.UniqueViolation, StringComparison.Ordinal)
            && string.Equals(pg.ConstraintName, "IX_stock_lots_item_id_lot_no", StringComparison.Ordinal);
    }

    private static string SerializeAuditDetail(
        string txNo,
        Guid warehouseId,
        Guid? locationId,
        DateTime occurredAtUtc,
        IReadOnlyList<StockMutationLine> lines)
    {
        var detail = new
        {
            txNo,
            warehouseId,
            locationId,
            occurredAtUtc,
            lineCount = lines.Count,
            lines = lines.Select(x => new
            {
                x.ItemId,
                Qty = Math.Abs(x.SignedQty),
                SignedQty = x.SignedQty,
                x.LotNo,
                x.SerialNo,
                x.ExpiryDate,
                x.UnitCost,
                x.Note
            })
        };

        return JsonSerializer.Serialize(detail);
    }

    private static string SerializeStockCountAuditDetail(
        string txNo,
        Guid warehouseId,
        Guid? locationId,
        DateTime occurredAtUtc,
        IReadOnlyList<StockCountLine> requestedLines,
        IReadOnlyList<AppliedStockCountLine> appliedLines)
    {
        var detail = new
        {
            txNo,
            warehouseId,
            locationId,
            occurredAtUtc,
            requestedLineCount = requestedLines.Count,
            appliedLineCount = appliedLines.Count,
            lines = appliedLines.Select(x => new
            {
                x.ItemId,
                x.CurrentQty,
                x.CountedQty,
                x.DiffQty,
                TxType = x.DiffQty > 0m ? InventoryTxType.AdjustIn : InventoryTxType.AdjustOut,
                x.Note
            })
        };

        return JsonSerializer.Serialize(detail);
    }

    private static DateTime NormalizeUtc(DateTime value)
    {
        if (value == default)
        {
            return DateTime.UtcNow;
        }

        return value.Kind == DateTimeKind.Utc ? value : value.ToUniversalTime();
    }

    private static Guid? NormalizeOptionalGuid(Guid? value)
    {
        if (!value.HasValue || value.Value == Guid.Empty)
        {
            return null;
        }

        return value.Value;
    }

    private static string? NormalizeTxNo(string? txNo)
    {
        return string.IsNullOrWhiteSpace(txNo) ? null : txNo.Trim();
    }

    private static void ValidateRequestedTxNo(string txNo, string prefix)
    {
        if (string.IsNullOrWhiteSpace(txNo))
        {
            return;
        }

        var escapedPrefix = Regex.Escape(prefix);
        var pattern = $"^{escapedPrefix}-\\d{{8}}-\\d{{4}}$";
        if (!Regex.IsMatch(txNo, pattern, RegexOptions.CultureInvariant))
        {
            throw new InvalidOperationException($"TxNo format must be '{prefix}-YYYYMMDD-####'.");
        }
    }

    private static string? NormalizeLotNo(string? lotNo)
    {
        return string.IsNullOrWhiteSpace(lotNo) ? null : lotNo.Trim();
    }

    private static string? NormalizeSerialNo(string? serialNo)
    {
        return string.IsNullOrWhiteSpace(serialNo) ? null : serialNo.Trim();
    }

    private static DateTime? NormalizeDate(DateTime? value)
    {
        if (!value.HasValue)
        {
            return null;
        }

        var normalized = value.Value.Kind switch
        {
            DateTimeKind.Utc => value.Value,
            DateTimeKind.Unspecified => DateTime.SpecifyKind(value.Value, DateTimeKind.Utc),
            _ => value.Value.ToUniversalTime()
        };

        return normalized.Date;
    }

    private sealed record StockMutationLine(
        Guid ItemId,
        decimal SignedQty,
        decimal? UnitCost,
        string? Note,
        string? LotNo,
        string? SerialNo,
        DateTime? ExpiryDate);

    private sealed record StockCountLine(
        Guid ItemId,
        decimal CountedQty,
        string? Note);

    private sealed record AppliedStockCountLine(
        Guid ItemId,
        decimal CurrentQty,
        decimal CountedQty,
        decimal DiffQty,
        string? Note);

    private sealed record StockLotKey(Guid ItemId, string LotNo);

    private sealed record TrackingResolution(
        Guid? LotId,
        string? SerialNo,
        DateTime? ExpiryDate);
}
